config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  scope "/admin" do
    resources :users
  end

  resources :locations do
    resources :schedule_locations
  end

  namespace :api, defaults: { format: :json } do
    post :schedule, to: 'scheduler#is_open_or_close_to_location'
  end
end

app/models/schedule_location.rb
class ScheduleLocation < ApplicationRecord

  DAYS_OF_WEEK = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

  belongs_to :location

  validates :open, presence: true
  validates :close, presence: true
  validates :day_of_week, presence: true, uniqueness: { scope: :location_id }, inclusion: { in: DAYS_OF_WEEK }

  def is_open?(time)
    modified_time = Time.utc(open.year, open.month, open.day, time.hour, time.min, time.sec)
    modified_time.between?(open, close)
  end
end

app/controllers/schedule_locations_controller.rb
class ScheduleLocationsController < ApplicationController
  before_action :set_schedule_location, only: [:show, :edit, :update, :destroy]
  before_action :set_location

  # GET /schedule_locations
  # GET /schedule_locations.json
  def index
    @schedule_locations = ScheduleLocation.where(location_id: @location.id)
  end

  # GET /schedule_locations/1
  # GET /schedule_locations/1.json
  def show
  end

  # GET /schedule_locations/new
  def new
    @schedule_location = ScheduleLocation.new
  end

  # GET /schedule_locations/1/edit
  def edit
  end

  # POST /schedule_locations
  # POST /schedule_locations.json
  def create
    @schedule_location = ScheduleLocation.new(schedule_location_params)

    respond_to do |format|
      if @schedule_location.save
        format.html { redirect_to location_schedule_locations_path(@location), notice: 'Schedule location was successfully created.' }
        format.json { render :show, status: :created, location: @schedule_location }
      else
        format.html { render :new }
        format.json { render json: @schedule_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedule_locations/1
  # PATCH/PUT /schedule_locations/1.json
  def update
    respond_to do |format|
      if @schedule_location.update(schedule_location_params)
        format.html { redirect_to location_schedule_locations_path(@location), notice: 'Schedule location was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule_location }
      else
        format.html { render :edit }
        format.json { render json: @schedule_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedule_locations/1
  # DELETE /schedule_locations/1.json
  def destroy
    @schedule_location.destroy
    respond_to do |format|
      format.html { redirect_to location_schedule_locations_url, notice: 'Schedule location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule_location
      @schedule_location = ScheduleLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_location_params
      params.require(:schedule_location).permit(:location_id, :open, :close, :day_of_week)
    end

    def set_location
      @location = Location.find(params[:location_id])
    end
end

app/helpers/schedule_locations_helper.rb
module ScheduleLocationsHelper
end

app/views/schedule_locations/_form.html.erb
<%= form_for [@location, @schedule_location] do |f| %>
  <% if schedule_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule_location.errors.count, "error") %> prohibited this schedule_location from being saved:</h2>

      <ul>
      <% schedule_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :location_id, { :value => @location.id } %>

  <div class="field">
    <%= f.label :day_of_week %>
    <%= f.select :day_of_week, ScheduleLocation::DAYS_OF_WEEK %>
  </div>

  <div class="field">
    <%= f.label :open %>
    <%= f.time_select :open %>
  </div>

  <div class="field">
    <%= f.label :close %>
    <%= f.time_select :close %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedule_locations/edit.html.erb
<h1>Editing Schedule Location</h1>

<%= render 'form', schedule_location: @schedule_location %>

<%= link_to 'Show', location_schedule_location_path %> |
<%= link_to 'Back', location_schedule_locations_path %>

app/views/schedule_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= "Schedule for #{@location.name}" %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Open</th>
      <th>Close</th>
      <th>Day of week</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedule_locations.each do |schedule_location| %>
      <tr>
        <td><%= schedule_location.open.strftime('%k:%M') %></td>
        <td><%= schedule_location.close.strftime('%k:%M') %></td>
        <td><%= schedule_location.day_of_week %></td>
        <td><%= link_to 'Edit', edit_location_schedule_location_path(@location.id, schedule_location) %></td>
        <td><%= link_to 'Destroy', location_schedule_location_path(@location.id, schedule_location), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="row">
  <div class="col-md-3">
    <%= link_to 'New Schedule Location', new_location_schedule_location_path %>
  </div>
  <div class="col-md-2">
    <%= link_to 'Back', locations_path %>
  </div>
</div>

app/views/schedule_locations/new.html.erb
<h1>New Schedule Location</h1>

<%= render 'form', schedule_location: @schedule_location %>

<%= link_to 'Back', location_schedule_locations_path %>

app/views/schedule_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Open:</strong>
  <%= @schedule_location.open %>
</p>

<p>
  <strong>Close:</strong>
  <%= @schedule_location.close %>
</p>

<p>
  <strong>Day of week:</strong>
  <%= @schedule_location.day_of_week %>
</p>

<%= link_to 'Edit', edit_location_schedule_location_path(@location, @schedule_location) %> |
<%= link_to 'Back', location_schedule_locations_path %>